# TODO : 아직 작업되지 않음 외부파라미터 세팅 필욧
lidar_camera_tf:
  ros__parameters:
    parent_frame: "velodyne"
    child_frame: "camera_right_frame"
    translation: [-0.0037, 0.3370, 0.4387]
    rotation: [0.0153, -0.7391, 0.0143, 0.6733]  # x, y, z, w
